name: CI
on: [push]

env:
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:
  Build-Win:

    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-2022

    steps:

      # Checkout our repository, so the job can access it
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

      # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore TapExtensions.sln

    - name: Build Solution
      run: msbuild TapExtensions.sln /property:Configuration=Release


  Build-Linux:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Show DotNet Version
      run: dotnet --version

    - name: Install Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build TapExtensions.sln --configuration Release --no-restore

    - name: Move Packages
      run: mv bin/Release/*.TapPackage .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TapPackage
        retention-days: 7
        path: "*.TapPackage"


  Build-MacOS:
    runs-on: macOS-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4

    - name: Show DotNet Version
      run: dotnet --version

    - name: Install Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build TapExtensions.sln --configuration Release --no-restore
