name: CI

on: [push]

env:
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:
  build:
  
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-2022
    strategy:
      matrix:
        Architecture: [x64]

    env:
      Solution_Name: TapExtensions.sln

    steps:
    
      # Checkout our repository, so the job can access it
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

      # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore TapExtensions.sln

    - name: Build the Solution
      run: msbuild TapExtensions.sln
